CREATE DATABASE granja_abejas IF NOT EXISTS;

\c granja-abejas;

DROP TABLE IF EXISTS clientes;
CREATE TABLE clientes (
	id_cliente SERIAL PRIMARY KEY ON DELETE CASCADE,
	nombre VARCHAR(100) NOT NULL,
	telefono VARCHAR(20),
	UBICACION TEXT
);

DROP TABLE IF EXISTS pedidos;
CREATE TABLE pedidos (
	id_pedidos SERIAL PRIMARY KEY ON DELETE CASCADE,
	fecha_log TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	fecha_pedido DATE NOT NULL DEFAULT CURRENT_DATE,
	descripcion VARCHAR(255),
	cantidad INT CHECK (cantidad > 0)
);

DROP TABLE IF EXISTS logs;
CREATE TABLE logs (
    id_log SERIAL PRIMARY KEY ON DELETE CASCADE,
    fecha_log TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    metodo VARCHAR(10) NOT NULL,
    ip VARCHAR(45) NOT NULL,
    url VARCHAR(255) NOT NULL
);